# Generated by Django 3.2.4 on 2021-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_number',
            field=models.URLField(),
        ),
    ]
